# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class BundleDataLinkInterface(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, sku: str=None, option_id: int=None, qty: float=None, position: int=None, is_default: bool=None, price: float=None, price_type: int=None, can_change_quantity: int=None):
        """
        BundleDataLinkInterface - a model defined in Swagger

        :param id: The id of this BundleDataLinkInterface.
        :type id: str
        :param sku: The sku of this BundleDataLinkInterface.
        :type sku: str
        :param option_id: The option_id of this BundleDataLinkInterface.
        :type option_id: int
        :param qty: The qty of this BundleDataLinkInterface.
        :type qty: float
        :param position: The position of this BundleDataLinkInterface.
        :type position: int
        :param is_default: The is_default of this BundleDataLinkInterface.
        :type is_default: bool
        :param price: The price of this BundleDataLinkInterface.
        :type price: float
        :param price_type: The price_type of this BundleDataLinkInterface.
        :type price_type: int
        :param can_change_quantity: The can_change_quantity of this BundleDataLinkInterface.
        :type can_change_quantity: int
        """
        self.swagger_types = {
            'id': str,
            'sku': str,
            'option_id': int,
            'qty': float,
            'position': int,
            'is_default': bool,
            'price': float,
            'price_type': int,
            'can_change_quantity': int
        }

        self.attribute_map = {
            'id': 'id',
            'sku': 'sku',
            'option_id': 'option_id',
            'qty': 'qty',
            'position': 'position',
            'is_default': 'is_default',
            'price': 'price',
            'price_type': 'price_type',
            'can_change_quantity': 'can_change_quantity'
        }

        self._id = id
        self._sku = sku
        self._option_id = option_id
        self._qty = qty
        self._position = position
        self._is_default = is_default
        self._price = price
        self._price_type = price_type
        self._can_change_quantity = can_change_quantity

    @classmethod
    def from_dict(cls, dikt) -> 'BundleDataLinkInterface':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bundle-data-link-interface of this BundleDataLinkInterface.
        :rtype: BundleDataLinkInterface
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this BundleDataLinkInterface.
        The identifier

        :return: The id of this BundleDataLinkInterface.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this BundleDataLinkInterface.
        The identifier

        :param id: The id of this BundleDataLinkInterface.
        :type id: str
        """

        self._id = id

    @property
    def sku(self) -> str:
        """
        Gets the sku of this BundleDataLinkInterface.
        Linked product sku

        :return: The sku of this BundleDataLinkInterface.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku: str):
        """
        Sets the sku of this BundleDataLinkInterface.
        Linked product sku

        :param sku: The sku of this BundleDataLinkInterface.
        :type sku: str
        """

        self._sku = sku

    @property
    def option_id(self) -> int:
        """
        Gets the option_id of this BundleDataLinkInterface.
        Option id

        :return: The option_id of this BundleDataLinkInterface.
        :rtype: int
        """
        return self._option_id

    @option_id.setter
    def option_id(self, option_id: int):
        """
        Sets the option_id of this BundleDataLinkInterface.
        Option id

        :param option_id: The option_id of this BundleDataLinkInterface.
        :type option_id: int
        """

        self._option_id = option_id

    @property
    def qty(self) -> float:
        """
        Gets the qty of this BundleDataLinkInterface.
        Qty

        :return: The qty of this BundleDataLinkInterface.
        :rtype: float
        """
        return self._qty

    @qty.setter
    def qty(self, qty: float):
        """
        Sets the qty of this BundleDataLinkInterface.
        Qty

        :param qty: The qty of this BundleDataLinkInterface.
        :type qty: float
        """

        self._qty = qty

    @property
    def position(self) -> int:
        """
        Gets the position of this BundleDataLinkInterface.
        Position

        :return: The position of this BundleDataLinkInterface.
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position: int):
        """
        Sets the position of this BundleDataLinkInterface.
        Position

        :param position: The position of this BundleDataLinkInterface.
        :type position: int
        """

        self._position = position

    @property
    def is_default(self) -> bool:
        """
        Gets the is_default of this BundleDataLinkInterface.
        Is default

        :return: The is_default of this BundleDataLinkInterface.
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default: bool):
        """
        Sets the is_default of this BundleDataLinkInterface.
        Is default

        :param is_default: The is_default of this BundleDataLinkInterface.
        :type is_default: bool
        """
        if is_default is None:
            raise ValueError("Invalid value for `is_default`, must not be `None`")

        self._is_default = is_default

    @property
    def price(self) -> float:
        """
        Gets the price of this BundleDataLinkInterface.
        Price

        :return: The price of this BundleDataLinkInterface.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """
        Sets the price of this BundleDataLinkInterface.
        Price

        :param price: The price of this BundleDataLinkInterface.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")

        self._price = price

    @property
    def price_type(self) -> int:
        """
        Gets the price_type of this BundleDataLinkInterface.
        Price type

        :return: The price_type of this BundleDataLinkInterface.
        :rtype: int
        """
        return self._price_type

    @price_type.setter
    def price_type(self, price_type: int):
        """
        Sets the price_type of this BundleDataLinkInterface.
        Price type

        :param price_type: The price_type of this BundleDataLinkInterface.
        :type price_type: int
        """
        if price_type is None:
            raise ValueError("Invalid value for `price_type`, must not be `None`")

        self._price_type = price_type

    @property
    def can_change_quantity(self) -> int:
        """
        Gets the can_change_quantity of this BundleDataLinkInterface.
        Whether quantity could be changed

        :return: The can_change_quantity of this BundleDataLinkInterface.
        :rtype: int
        """
        return self._can_change_quantity

    @can_change_quantity.setter
    def can_change_quantity(self, can_change_quantity: int):
        """
        Sets the can_change_quantity of this BundleDataLinkInterface.
        Whether quantity could be changed

        :param can_change_quantity: The can_change_quantity of this BundleDataLinkInterface.
        :type can_change_quantity: int
        """

        self._can_change_quantity = can_change_quantity

