//
// CatalogInventoryDataStockStatusInterface.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Interface StockStatusInterface */
open class CatalogInventoryDataStockStatusInterface: JSONEncodable {
    public var productId: Int32?
    public var stockId: Int32?
    public var qty: Int32?
    public var stockStatus: Int32?
    public var stockItem: CatalogInventoryDataStockItemInterface?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["product_id"] = self.productId?.encodeToJSON()
        nillableDictionary["stock_id"] = self.stockId?.encodeToJSON()
        nillableDictionary["qty"] = self.qty?.encodeToJSON()
        nillableDictionary["stock_status"] = self.stockStatus?.encodeToJSON()
        nillableDictionary["stock_item"] = self.stockItem?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
