//
// CatalogProductWebsiteLinkInterface.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
open class CatalogProductWebsiteLinkInterface: JSONEncodable {
    public var sku: String?
    /** Website ids */
    public var websiteId: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["website_id"] = self.websiteId?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
