//
// CatalogDataProductSearchResultsInterface.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
open class CatalogDataProductSearchResultsInterface: JSONEncodable {
    /** Attributes list. */
    public var items: [Product]?
    public var searchCriteria: FrameworkSearchCriteriaInterface?
    /** Total count. */
    public var totalCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["items"] = self.items?.encodeToJSON()
        nillableDictionary["search_criteria"] = self.searchCriteria?.encodeToJSON()
        nillableDictionary["total_count"] = self.totalCount?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
