//
// FrameworkSearchFilterGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Groups two or more filters together using a logical OR */
open class FrameworkSearchFilterGroup: JSONEncodable {
    /** A list of filters in this group */
    public var filters: [FrameworkFilter]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["filters"] = self.filters?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
