# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class EavDataAttributeOptionLabelInterface(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, store_id: int=None, label: str=None):
        """
        EavDataAttributeOptionLabelInterface - a model defined in Swagger

        :param store_id: The store_id of this EavDataAttributeOptionLabelInterface.
        :type store_id: int
        :param label: The label of this EavDataAttributeOptionLabelInterface.
        :type label: str
        """
        self.swagger_types = {
            'store_id': int,
            'label': str
        }

        self.attribute_map = {
            'store_id': 'store_id',
            'label': 'label'
        }

        self._store_id = store_id
        self._label = label

    @classmethod
    def from_dict(cls, dikt) -> 'EavDataAttributeOptionLabelInterface':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The eav-data-attribute-option-label-interface of this EavDataAttributeOptionLabelInterface.
        :rtype: EavDataAttributeOptionLabelInterface
        """
        return deserialize_model(dikt, cls)

    @property
    def store_id(self) -> int:
        """
        Gets the store_id of this EavDataAttributeOptionLabelInterface.
        Store id

        :return: The store_id of this EavDataAttributeOptionLabelInterface.
        :rtype: int
        """
        return self._store_id

    @store_id.setter
    def store_id(self, store_id: int):
        """
        Sets the store_id of this EavDataAttributeOptionLabelInterface.
        Store id

        :param store_id: The store_id of this EavDataAttributeOptionLabelInterface.
        :type store_id: int
        """

        self._store_id = store_id

    @property
    def label(self) -> str:
        """
        Gets the label of this EavDataAttributeOptionLabelInterface.
        Option label

        :return: The label of this EavDataAttributeOptionLabelInterface.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """
        Sets the label of this EavDataAttributeOptionLabelInterface.
        Option label

        :param label: The label of this EavDataAttributeOptionLabelInterface.
        :type label: str
        """

        self._label = label

