swagger: "2.0"
info:
  description: |
    This is a Shoppers Catalogue server.

    [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.

    For this sample, you can use the api key `special-key` to test the authorization filters
  version: "1.0.0"
  title: Shoppers OpenAPI
  termsOfService: http://helloreverb.com/terms/
  contact:
    name: harjeetss@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: shoppers.io
basePath: /v2
schemes:
  - http
paths:
  /v1/products:
    post:
      tags:
        - product
      summary: Add a new product to the store
      description: ""
      operationId: addProduct
      security:
        - shoppers_auth:
          - write_products
          - read_products
  /v1/products/findByCategory:
    get:
      tags:
        - product
      summary: Finds Products by category
      description: Use category1 for testing.
      operationId: findProductsByCategories
      security:
        - shoppers_auth:
          - write_products
          - read_products
  /v1/products/{productId}:
    get:
      tags:
        - product
      summary: Find product by ID
      description: Returns a product when ID < 10.  ID > 10 or nonintegers will simulate API error conditions
      operationId: getProductById
      security:
        - api_key: []
        - shoppers_auth:
          - write_products
          - read_products
    post:
      tags:
        - product
      summary: Updates a product in the store with form data
      description: ""
      operationId: updateProductWithForm
      security:
        - shoppers_auth:
          - write_products
          - read_products
    delete:
      tags:
        - product
      summary: Deletes a product
      description: ""
      operationId: deleteProduct
      security:
        - shoppers_auth:
          - write_products
          - read_products
  '/v1/products/{sku}/websites':
    post:
      tags:
        - catalogProductWebsiteLinkRepositoryV1
      description: Assign a product to the website
      operationId: catalogProductWebsiteLinkRepositoryV1SavePost
    put:
      tags:
        - catalogProductWebsiteLinkRepositoryV1
      description: Assign a product to the website
      operationId: catalogProductWebsiteLinkRepositoryV1SavePut
  '/v1/products/{sku}/websites/{websiteId}':
    delete:
      tags:
        - catalogProductWebsiteLinkRepositoryV1
      description: Remove the website assignment from the product by product sku
      operationId: catalogProductWebsiteLinkRepositoryV1DeleteByIdDelete
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
  shoppers_auth:
    type: oauth2
    authorizationUrl: http://shoppers.io/api/oauth/dialog
    flow: implicit
    scopes:
      write_products: modify products in your account
      read_products: read your products