//
// BundleDataOptionInterface.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Interface OptionInterface */
open class BundleDataOptionInterface: JSONEncodable {
    /** Option id */
    public var optionId: Int32?
    /** Option title */
    public var title: String?
    /** Is required option */
    public var _required: Bool?
    /** Input type */
    public var type: String?
    /** Option position */
    public var position: Int32?
    /** Product sku */
    public var sku: String?
    /** Product links */
    public var productLinks: [BundleDataLinkInterface]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["option_id"] = self.optionId?.encodeToJSON()
        nillableDictionary["title"] = self.title
        nillableDictionary["required"] = self._required
        nillableDictionary["type"] = self.type
        nillableDictionary["position"] = self.position?.encodeToJSON()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["product_links"] = self.productLinks?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
