//
// ErrorParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Error parameters list */
public typealias ErrorParameters = [ErrorParametersItem]
