//
// ProductLinkInterface.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
open class ProductLinkInterface: JSONEncodable {
    /** SKU */
    public var sku: String?
    /** Link type */
    public var linkType: String?
    /** Linked product sku */
    public var linkedProductSku: String?
    /** Linked product type (simple, virtual, etc) */
    public var linkedProductType: String?
    /** Linked item position */
    public var position: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["link_type"] = self.linkType
        nillableDictionary["linked_product_sku"] = self.linkedProductSku
        nillableDictionary["linked_product_type"] = self.linkedProductType
        nillableDictionary["position"] = self.position?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
