//
// ProductCustomOptionValuesInterface.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
open class ProductCustomOptionValuesInterface: JSONEncodable {
    /** Option title */
    public var title: String?
    /** Sort order */
    public var sortOrder: Int32?
    /** Price */
    public var price: Double?
    /** Price type */
    public var priceType: String?
    /** Sku */
    public var sku: String?
    /** Option type id */
    public var optionTypeId: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["title"] = self.title
        nillableDictionary["sort_order"] = self.sortOrder?.encodeToJSON()
        nillableDictionary["price"] = self.price
        nillableDictionary["price_type"] = self.priceType
        nillableDictionary["sku"] = self.sku
        nillableDictionary["option_type_id"] = self.optionTypeId?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
