# coding: utf-8

"""
    Shoppers OpenAPI

    This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.bundle_data_link_interface import BundleDataLinkInterface
from .models.bundle_data_option_interface import BundleDataOptionInterface
from .models.category import Category
from .models.configurable_product_data_option_interface import ConfigurableProductDataOptionInterface
from .models.configurable_product_data_option_value_interface import ConfigurableProductDataOptionValueInterface
from .models.error_errors import ErrorErrors
from .models.error_errors_item import ErrorErrorsItem
from .models.error_parameters import ErrorParameters
from .models.error_parameters_item import ErrorParametersItem
from .models.error_response import ErrorResponse
from .models.framework_attribute_interface import FrameworkAttributeInterface
from .models.inventory_data_stock_item_interface import InventoryDataStockItemInterface
from .models.product import Product
from .models.product_custom_option_interface import ProductCustomOptionInterface
from .models.product_custom_option_values_interface import ProductCustomOptionValuesInterface
from .models.product_extension_interface import ProductExtensionInterface
from .models.product_link_interface import ProductLinkInterface
from .models.product_tier_price_interface import ProductTierPriceInterface

# import apis into sdk package
from .apis.catalog_product_tier_price_management_v1_api import CatalogProductTierPriceManagementV1Api

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
