# coding: utf-8

"""
    Shoppers OpenAPI

    This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ProductCustomOptionInterface(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, product_sku=None, option_id=None, title=None, type=None, sort_order=None, is_require=None, price=None, price_type=None, sku=None, file_extension=None, max_characters=None, image_size_x=None, image_size_y=None, values=None):
        """
        ProductCustomOptionInterface - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'product_sku': 'str',
            'option_id': 'int',
            'title': 'str',
            'type': 'str',
            'sort_order': 'int',
            'is_require': 'bool',
            'price': 'float',
            'price_type': 'str',
            'sku': 'str',
            'file_extension': 'str',
            'max_characters': 'int',
            'image_size_x': 'int',
            'image_size_y': 'int',
            'values': 'list[ProductCustomOptionValuesInterface]'
        }

        self.attribute_map = {
            'product_sku': 'product_sku',
            'option_id': 'option_id',
            'title': 'title',
            'type': 'type',
            'sort_order': 'sort_order',
            'is_require': 'is_require',
            'price': 'price',
            'price_type': 'price_type',
            'sku': 'sku',
            'file_extension': 'file_extension',
            'max_characters': 'max_characters',
            'image_size_x': 'image_size_x',
            'image_size_y': 'image_size_y',
            'values': 'values'
        }

        self._product_sku = product_sku
        self._option_id = option_id
        self._title = title
        self._type = type
        self._sort_order = sort_order
        self._is_require = is_require
        self._price = price
        self._price_type = price_type
        self._sku = sku
        self._file_extension = file_extension
        self._max_characters = max_characters
        self._image_size_x = image_size_x
        self._image_size_y = image_size_y
        self._values = values

    @property
    def product_sku(self):
        """
        Gets the product_sku of this ProductCustomOptionInterface.
        Product SKU

        :return: The product_sku of this ProductCustomOptionInterface.
        :rtype: str
        """
        return self._product_sku

    @product_sku.setter
    def product_sku(self, product_sku):
        """
        Sets the product_sku of this ProductCustomOptionInterface.
        Product SKU

        :param product_sku: The product_sku of this ProductCustomOptionInterface.
        :type: str
        """
        if product_sku is None:
            raise ValueError("Invalid value for `product_sku`, must not be `None`")

        self._product_sku = product_sku

    @property
    def option_id(self):
        """
        Gets the option_id of this ProductCustomOptionInterface.
        Option id

        :return: The option_id of this ProductCustomOptionInterface.
        :rtype: int
        """
        return self._option_id

    @option_id.setter
    def option_id(self, option_id):
        """
        Sets the option_id of this ProductCustomOptionInterface.
        Option id

        :param option_id: The option_id of this ProductCustomOptionInterface.
        :type: int
        """

        self._option_id = option_id

    @property
    def title(self):
        """
        Gets the title of this ProductCustomOptionInterface.
        Option title

        :return: The title of this ProductCustomOptionInterface.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this ProductCustomOptionInterface.
        Option title

        :param title: The title of this ProductCustomOptionInterface.
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")

        self._title = title

    @property
    def type(self):
        """
        Gets the type of this ProductCustomOptionInterface.
        Option type

        :return: The type of this ProductCustomOptionInterface.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ProductCustomOptionInterface.
        Option type

        :param type: The type of this ProductCustomOptionInterface.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def sort_order(self):
        """
        Gets the sort_order of this ProductCustomOptionInterface.
        Sort order

        :return: The sort_order of this ProductCustomOptionInterface.
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order):
        """
        Sets the sort_order of this ProductCustomOptionInterface.
        Sort order

        :param sort_order: The sort_order of this ProductCustomOptionInterface.
        :type: int
        """
        if sort_order is None:
            raise ValueError("Invalid value for `sort_order`, must not be `None`")

        self._sort_order = sort_order

    @property
    def is_require(self):
        """
        Gets the is_require of this ProductCustomOptionInterface.
        Is require

        :return: The is_require of this ProductCustomOptionInterface.
        :rtype: bool
        """
        return self._is_require

    @is_require.setter
    def is_require(self, is_require):
        """
        Sets the is_require of this ProductCustomOptionInterface.
        Is require

        :param is_require: The is_require of this ProductCustomOptionInterface.
        :type: bool
        """
        if is_require is None:
            raise ValueError("Invalid value for `is_require`, must not be `None`")

        self._is_require = is_require

    @property
    def price(self):
        """
        Gets the price of this ProductCustomOptionInterface.
        Price

        :return: The price of this ProductCustomOptionInterface.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """
        Sets the price of this ProductCustomOptionInterface.
        Price

        :param price: The price of this ProductCustomOptionInterface.
        :type: float
        """

        self._price = price

    @property
    def price_type(self):
        """
        Gets the price_type of this ProductCustomOptionInterface.
        Price type

        :return: The price_type of this ProductCustomOptionInterface.
        :rtype: str
        """
        return self._price_type

    @price_type.setter
    def price_type(self, price_type):
        """
        Sets the price_type of this ProductCustomOptionInterface.
        Price type

        :param price_type: The price_type of this ProductCustomOptionInterface.
        :type: str
        """

        self._price_type = price_type

    @property
    def sku(self):
        """
        Gets the sku of this ProductCustomOptionInterface.
        Sku

        :return: The sku of this ProductCustomOptionInterface.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """
        Sets the sku of this ProductCustomOptionInterface.
        Sku

        :param sku: The sku of this ProductCustomOptionInterface.
        :type: str
        """

        self._sku = sku

    @property
    def file_extension(self):
        """
        Gets the file_extension of this ProductCustomOptionInterface.

        :return: The file_extension of this ProductCustomOptionInterface.
        :rtype: str
        """
        return self._file_extension

    @file_extension.setter
    def file_extension(self, file_extension):
        """
        Sets the file_extension of this ProductCustomOptionInterface.

        :param file_extension: The file_extension of this ProductCustomOptionInterface.
        :type: str
        """

        self._file_extension = file_extension

    @property
    def max_characters(self):
        """
        Gets the max_characters of this ProductCustomOptionInterface.

        :return: The max_characters of this ProductCustomOptionInterface.
        :rtype: int
        """
        return self._max_characters

    @max_characters.setter
    def max_characters(self, max_characters):
        """
        Sets the max_characters of this ProductCustomOptionInterface.

        :param max_characters: The max_characters of this ProductCustomOptionInterface.
        :type: int
        """

        self._max_characters = max_characters

    @property
    def image_size_x(self):
        """
        Gets the image_size_x of this ProductCustomOptionInterface.

        :return: The image_size_x of this ProductCustomOptionInterface.
        :rtype: int
        """
        return self._image_size_x

    @image_size_x.setter
    def image_size_x(self, image_size_x):
        """
        Sets the image_size_x of this ProductCustomOptionInterface.

        :param image_size_x: The image_size_x of this ProductCustomOptionInterface.
        :type: int
        """

        self._image_size_x = image_size_x

    @property
    def image_size_y(self):
        """
        Gets the image_size_y of this ProductCustomOptionInterface.

        :return: The image_size_y of this ProductCustomOptionInterface.
        :rtype: int
        """
        return self._image_size_y

    @image_size_y.setter
    def image_size_y(self, image_size_y):
        """
        Sets the image_size_y of this ProductCustomOptionInterface.

        :param image_size_y: The image_size_y of this ProductCustomOptionInterface.
        :type: int
        """

        self._image_size_y = image_size_y

    @property
    def values(self):
        """
        Gets the values of this ProductCustomOptionInterface.

        :return: The values of this ProductCustomOptionInterface.
        :rtype: list[ProductCustomOptionValuesInterface]
        """
        return self._values

    @values.setter
    def values(self, values):
        """
        Sets the values of this ProductCustomOptionInterface.

        :param values: The values of this ProductCustomOptionInterface.
        :type: list[ProductCustomOptionValuesInterface]
        """

        self._values = values

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
