# coding: utf-8

"""
    Shoppers OpenAPI

    This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ProductLinkInterface(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, sku=None, link_type=None, linked_product_sku=None, linked_product_type=None, position=None):
        """
        ProductLinkInterface - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'sku': 'str',
            'link_type': 'str',
            'linked_product_sku': 'str',
            'linked_product_type': 'str',
            'position': 'int'
        }

        self.attribute_map = {
            'sku': 'sku',
            'link_type': 'link_type',
            'linked_product_sku': 'linked_product_sku',
            'linked_product_type': 'linked_product_type',
            'position': 'position'
        }

        self._sku = sku
        self._link_type = link_type
        self._linked_product_sku = linked_product_sku
        self._linked_product_type = linked_product_type
        self._position = position

    @property
    def sku(self):
        """
        Gets the sku of this ProductLinkInterface.
        SKU

        :return: The sku of this ProductLinkInterface.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """
        Sets the sku of this ProductLinkInterface.
        SKU

        :param sku: The sku of this ProductLinkInterface.
        :type: str
        """
        if sku is None:
            raise ValueError("Invalid value for `sku`, must not be `None`")

        self._sku = sku

    @property
    def link_type(self):
        """
        Gets the link_type of this ProductLinkInterface.
        Link type

        :return: The link_type of this ProductLinkInterface.
        :rtype: str
        """
        return self._link_type

    @link_type.setter
    def link_type(self, link_type):
        """
        Sets the link_type of this ProductLinkInterface.
        Link type

        :param link_type: The link_type of this ProductLinkInterface.
        :type: str
        """
        if link_type is None:
            raise ValueError("Invalid value for `link_type`, must not be `None`")

        self._link_type = link_type

    @property
    def linked_product_sku(self):
        """
        Gets the linked_product_sku of this ProductLinkInterface.
        Linked product sku

        :return: The linked_product_sku of this ProductLinkInterface.
        :rtype: str
        """
        return self._linked_product_sku

    @linked_product_sku.setter
    def linked_product_sku(self, linked_product_sku):
        """
        Sets the linked_product_sku of this ProductLinkInterface.
        Linked product sku

        :param linked_product_sku: The linked_product_sku of this ProductLinkInterface.
        :type: str
        """
        if linked_product_sku is None:
            raise ValueError("Invalid value for `linked_product_sku`, must not be `None`")

        self._linked_product_sku = linked_product_sku

    @property
    def linked_product_type(self):
        """
        Gets the linked_product_type of this ProductLinkInterface.
        Linked product type (simple, virtual, etc)

        :return: The linked_product_type of this ProductLinkInterface.
        :rtype: str
        """
        return self._linked_product_type

    @linked_product_type.setter
    def linked_product_type(self, linked_product_type):
        """
        Sets the linked_product_type of this ProductLinkInterface.
        Linked product type (simple, virtual, etc)

        :param linked_product_type: The linked_product_type of this ProductLinkInterface.
        :type: str
        """
        if linked_product_type is None:
            raise ValueError("Invalid value for `linked_product_type`, must not be `None`")

        self._linked_product_type = linked_product_type

    @property
    def position(self):
        """
        Gets the position of this ProductLinkInterface.
        Linked item position

        :return: The position of this ProductLinkInterface.
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """
        Sets the position of this ProductLinkInterface.
        Linked item position

        :param position: The position of this ProductLinkInterface.
        :type: int
        """
        if position is None:
            raise ValueError("Invalid value for `position`, must not be `None`")

        self._position = position

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
