/**
 * Shoppers OpenAPI
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Error parameters item
 **/
@ApiModel(description = "Error parameters item")
public class ErrorParametersItem {
  
  @SerializedName("resources")
  private String resources = null;
  @SerializedName("fieldName")
  private String fieldName = null;
  @SerializedName("fieldValue")
  private String fieldValue = null;

  /**
   * ACL resource
   **/
  @ApiModelProperty(value = "ACL resource")
  public String getResources() {
    return resources;
  }
  public void setResources(String resources) {
    this.resources = resources;
  }

  /**
   * Missing or invalid field name
   **/
  @ApiModelProperty(value = "Missing or invalid field name")
  public String getFieldName() {
    return fieldName;
  }
  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  /**
   * Incorrect field value
   **/
  @ApiModelProperty(value = "Incorrect field value")
  public String getFieldValue() {
    return fieldValue;
  }
  public void setFieldValue(String fieldValue) {
    this.fieldValue = fieldValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorParametersItem errorParametersItem = (ErrorParametersItem) o;
    return (this.resources == null ? errorParametersItem.resources == null : this.resources.equals(errorParametersItem.resources)) &&
        (this.fieldName == null ? errorParametersItem.fieldName == null : this.fieldName.equals(errorParametersItem.fieldName)) &&
        (this.fieldValue == null ? errorParametersItem.fieldValue == null : this.fieldValue.equals(errorParametersItem.fieldValue));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.resources == null ? 0: this.resources.hashCode());
    result = 31 * result + (this.fieldName == null ? 0: this.fieldName.hashCode());
    result = 31 * result + (this.fieldValue == null ? 0: this.fieldValue.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorParametersItem {\n");
    
    sb.append("  resources: ").append(resources).append("\n");
    sb.append("  fieldName: ").append(fieldName).append("\n");
    sb.append("  fieldValue: ").append(fieldValue).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
