/*
 * Shoppers OpenAPI
 *
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DownloadableDataSampleInterface :  IEquatable<DownloadableDataSampleInterface>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DownloadableDataSampleInterface" /> class.
        /// </summary>
        /// <param name="Id">Sample(or link) id.</param>
        /// <param name="Title">Title (required).</param>
        /// <param name="SortOrder">Order index for sample (required).</param>
        /// <param name="SampleType">SampleType (required).</param>
        /// <param name="SampleFile">relative file path.</param>
        /// <param name="SampleFileContent">SampleFileContent.</param>
        /// <param name="SampleUrl">file URL.</param>
        public DownloadableDataSampleInterface(int? Id = null, string Title = null, int? SortOrder = null, string SampleType = null, string SampleFile = null, DownloadableDataFileContentInterface SampleFileContent = null, string SampleUrl = null)
        {
            // to ensure "Title" is required (not null)
            if (Title == null)
            {
                throw new InvalidDataException("Title is a required property for DownloadableDataSampleInterface and cannot be null");
            }
            else
            {
                this.Title = Title;
            }
            // to ensure "SortOrder" is required (not null)
            if (SortOrder == null)
            {
                throw new InvalidDataException("SortOrder is a required property for DownloadableDataSampleInterface and cannot be null");
            }
            else
            {
                this.SortOrder = SortOrder;
            }
            // to ensure "SampleType" is required (not null)
            if (SampleType == null)
            {
                throw new InvalidDataException("SampleType is a required property for DownloadableDataSampleInterface and cannot be null");
            }
            else
            {
                this.SampleType = SampleType;
            }
            this.Id = Id;
            this.SampleFile = SampleFile;
            this.SampleFileContent = SampleFileContent;
            this.SampleUrl = SampleUrl;
            
        }

        /// <summary>
        /// Sample(or link) id
        /// </summary>
        /// <value>Sample(or link) id</value>
        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Title
        /// </summary>
        /// <value>Title</value>
        [DataMember(Name="title")]
        public string Title { get; set; }

        /// <summary>
        /// Order index for sample
        /// </summary>
        /// <value>Order index for sample</value>
        [DataMember(Name="sort_order")]
        public int? SortOrder { get; set; }

        /// <summary>
        /// Gets or Sets SampleType
        /// </summary>
        [DataMember(Name="sample_type")]
        public string SampleType { get; set; }

        /// <summary>
        /// relative file path
        /// </summary>
        /// <value>relative file path</value>
        [DataMember(Name="sample_file")]
        public string SampleFile { get; set; }

        /// <summary>
        /// Gets or Sets SampleFileContent
        /// </summary>
        [DataMember(Name="sample_file_content")]
        public DownloadableDataFileContentInterface SampleFileContent { get; set; }

        /// <summary>
        /// file URL
        /// </summary>
        /// <value>file URL</value>
        [DataMember(Name="sample_url")]
        public string SampleUrl { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DownloadableDataSampleInterface {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  SortOrder: ").Append(SortOrder).Append("\n");
            sb.Append("  SampleType: ").Append(SampleType).Append("\n");
            sb.Append("  SampleFile: ").Append(SampleFile).Append("\n");
            sb.Append("  SampleFileContent: ").Append(SampleFileContent).Append("\n");
            sb.Append("  SampleUrl: ").Append(SampleUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((DownloadableDataSampleInterface)obj);
        }

        /// <summary>
        /// Returns true if DownloadableDataSampleInterface instances are equal
        /// </summary>
        /// <param name="other">Instance of DownloadableDataSampleInterface to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DownloadableDataSampleInterface other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Title == other.Title ||
                    this.Title != null &&
                    this.Title.Equals(other.Title)
                ) && 
                (
                    this.SortOrder == other.SortOrder ||
                    this.SortOrder != null &&
                    this.SortOrder.Equals(other.SortOrder)
                ) && 
                (
                    this.SampleType == other.SampleType ||
                    this.SampleType != null &&
                    this.SampleType.Equals(other.SampleType)
                ) && 
                (
                    this.SampleFile == other.SampleFile ||
                    this.SampleFile != null &&
                    this.SampleFile.Equals(other.SampleFile)
                ) && 
                (
                    this.SampleFileContent == other.SampleFileContent ||
                    this.SampleFileContent != null &&
                    this.SampleFileContent.Equals(other.SampleFileContent)
                ) && 
                (
                    this.SampleUrl == other.SampleUrl ||
                    this.SampleUrl != null &&
                    this.SampleUrl.Equals(other.SampleUrl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                    if (this.Title != null)
                    hash = hash * 59 + this.Title.GetHashCode();
                    if (this.SortOrder != null)
                    hash = hash * 59 + this.SortOrder.GetHashCode();
                    if (this.SampleType != null)
                    hash = hash * 59 + this.SampleType.GetHashCode();
                    if (this.SampleFile != null)
                    hash = hash * 59 + this.SampleFile.GetHashCode();
                    if (this.SampleFileContent != null)
                    hash = hash * 59 + this.SampleFileContent.GetHashCode();
                    if (this.SampleUrl != null)
                    hash = hash * 59 + this.SampleUrl.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(DownloadableDataSampleInterface left, DownloadableDataSampleInterface right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DownloadableDataSampleInterface left, DownloadableDataSampleInterface right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
