/*
 * Shoppers OpenAPI
 *
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// Groups two or more filters together using a logical OR
    /// </summary>
    [DataContract]
    public partial class FrameworkSearchFilterGroup :  IEquatable<FrameworkSearchFilterGroup>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FrameworkSearchFilterGroup" /> class.
        /// </summary>
        /// <param name="Filters">A list of filters in this group.</param>
        public FrameworkSearchFilterGroup(List<FrameworkFilter> Filters = null)
        {
            this.Filters = Filters;
            
        }

        /// <summary>
        /// A list of filters in this group
        /// </summary>
        /// <value>A list of filters in this group</value>
        [DataMember(Name="filters")]
        public List<FrameworkFilter> Filters { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FrameworkSearchFilterGroup {\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((FrameworkSearchFilterGroup)obj);
        }

        /// <summary>
        /// Returns true if FrameworkSearchFilterGroup instances are equal
        /// </summary>
        /// <param name="other">Instance of FrameworkSearchFilterGroup to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FrameworkSearchFilterGroup other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Filters == other.Filters ||
                    this.Filters != null &&
                    this.Filters.SequenceEqual(other.Filters)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Filters != null)
                    hash = hash * 59 + this.Filters.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(FrameworkSearchFilterGroup left, FrameworkSearchFilterGroup right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FrameworkSearchFilterGroup left, FrameworkSearchFilterGroup right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
