/**
 * Shoppers OpenAPI
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Product;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body {
  
  @SerializedName("product")
  private Product product = null;
  @SerializedName("saveOptions")
  private Boolean saveOptions = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Product getProduct() {
    return product;
  }
  public void setProduct(Product product) {
    this.product = product;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSaveOptions() {
    return saveOptions;
  }
  public void setSaveOptions(Boolean saveOptions) {
    this.saveOptions = saveOptions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body body = (Body) o;
    return (this.product == null ? body.product == null : this.product.equals(body.product)) &&
        (this.saveOptions == null ? body.saveOptions == null : this.saveOptions.equals(body.saveOptions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.product == null ? 0: this.product.hashCode());
    result = 31 * result + (this.saveOptions == null ? 0: this.saveOptions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body {\n");
    
    sb.append("  product: ").append(product).append("\n");
    sb.append("  saveOptions: ").append(saveOptions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
