/**
 * Shoppers OpenAPI
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.CatalogProductWebsiteLinkInterface;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body2 {
  
  @SerializedName("productWebsiteLink")
  private CatalogProductWebsiteLinkInterface productWebsiteLink = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public CatalogProductWebsiteLinkInterface getProductWebsiteLink() {
    return productWebsiteLink;
  }
  public void setProductWebsiteLink(CatalogProductWebsiteLinkInterface productWebsiteLink) {
    this.productWebsiteLink = productWebsiteLink;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body2 body2 = (Body2) o;
    return (this.productWebsiteLink == null ? body2.productWebsiteLink == null : this.productWebsiteLink.equals(body2.productWebsiteLink));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.productWebsiteLink == null ? 0: this.productWebsiteLink.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body2 {\n");
    
    sb.append("  productWebsiteLink: ").append(productWebsiteLink).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
