/**
 * Shoppers OpenAPI
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * 
 **/
@ApiModel(description = "")
public class CatalogProductWebsiteLinkInterface {
  
  @SerializedName("sku")
  private String sku = null;
  @SerializedName("website_id")
  private Integer websiteId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getSku() {
    return sku;
  }
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   * Website ids
   **/
  @ApiModelProperty(required = true, value = "Website ids")
  public Integer getWebsiteId() {
    return websiteId;
  }
  public void setWebsiteId(Integer websiteId) {
    this.websiteId = websiteId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogProductWebsiteLinkInterface catalogProductWebsiteLinkInterface = (CatalogProductWebsiteLinkInterface) o;
    return (this.sku == null ? catalogProductWebsiteLinkInterface.sku == null : this.sku.equals(catalogProductWebsiteLinkInterface.sku)) &&
        (this.websiteId == null ? catalogProductWebsiteLinkInterface.websiteId == null : this.websiteId.equals(catalogProductWebsiteLinkInterface.websiteId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sku == null ? 0: this.sku.hashCode());
    result = 31 * result + (this.websiteId == null ? 0: this.websiteId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogProductWebsiteLinkInterface {\n");
    
    sb.append("  sku: ").append(sku).append("\n");
    sb.append("  websiteId: ").append(websiteId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
