/**
 * Shoppers OpenAPI
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.DownloadableDataFileContentInterface;
import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * 
 **/
@ApiModel(description = "")
public class DownloadableDataLinkInterface {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("sort_order")
  private Integer sortOrder = null;
  @SerializedName("is_shareable")
  private Integer isShareable = null;
  @SerializedName("price")
  private BigDecimal price = null;
  @SerializedName("number_of_downloads")
  private Integer numberOfDownloads = null;
  @SerializedName("link_type")
  private String linkType = null;
  @SerializedName("link_file")
  private String linkFile = null;
  @SerializedName("link_file_content")
  private DownloadableDataFileContentInterface linkFileContent = null;
  @SerializedName("link_url")
  private String linkUrl = null;
  @SerializedName("sample_type")
  private String sampleType = null;
  @SerializedName("sample_file")
  private String sampleFile = null;
  @SerializedName("sample_file_content")
  private DownloadableDataFileContentInterface sampleFileContent = null;
  @SerializedName("sample_url")
  private String sampleUrl = null;

  /**
   * Sample(or link) id
   **/
  @ApiModelProperty(value = "Sample(or link) id")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getSortOrder() {
    return sortOrder;
  }
  public void setSortOrder(Integer sortOrder) {
    this.sortOrder = sortOrder;
  }

  /**
   * Shareable status
   **/
  @ApiModelProperty(required = true, value = "Shareable status")
  public Integer getIsShareable() {
    return isShareable;
  }
  public void setIsShareable(Integer isShareable) {
    this.isShareable = isShareable;
  }

  /**
   * Price
   **/
  @ApiModelProperty(required = true, value = "Price")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   * Of downloads per user
   **/
  @ApiModelProperty(value = "Of downloads per user")
  public Integer getNumberOfDownloads() {
    return numberOfDownloads;
  }
  public void setNumberOfDownloads(Integer numberOfDownloads) {
    this.numberOfDownloads = numberOfDownloads;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getLinkType() {
    return linkType;
  }
  public void setLinkType(String linkType) {
    this.linkType = linkType;
  }

  /**
   * relative file path
   **/
  @ApiModelProperty(value = "relative file path")
  public String getLinkFile() {
    return linkFile;
  }
  public void setLinkFile(String linkFile) {
    this.linkFile = linkFile;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DownloadableDataFileContentInterface getLinkFileContent() {
    return linkFileContent;
  }
  public void setLinkFileContent(DownloadableDataFileContentInterface linkFileContent) {
    this.linkFileContent = linkFileContent;
  }

  /**
   * Link url or null when type is 'file'
   **/
  @ApiModelProperty(value = "Link url or null when type is 'file'")
  public String getLinkUrl() {
    return linkUrl;
  }
  public void setLinkUrl(String linkUrl) {
    this.linkUrl = linkUrl;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getSampleType() {
    return sampleType;
  }
  public void setSampleType(String sampleType) {
    this.sampleType = sampleType;
  }

  /**
   * relative file path
   **/
  @ApiModelProperty(value = "relative file path")
  public String getSampleFile() {
    return sampleFile;
  }
  public void setSampleFile(String sampleFile) {
    this.sampleFile = sampleFile;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DownloadableDataFileContentInterface getSampleFileContent() {
    return sampleFileContent;
  }
  public void setSampleFileContent(DownloadableDataFileContentInterface sampleFileContent) {
    this.sampleFileContent = sampleFileContent;
  }

  /**
   * file URL
   **/
  @ApiModelProperty(value = "file URL")
  public String getSampleUrl() {
    return sampleUrl;
  }
  public void setSampleUrl(String sampleUrl) {
    this.sampleUrl = sampleUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DownloadableDataLinkInterface downloadableDataLinkInterface = (DownloadableDataLinkInterface) o;
    return (this.id == null ? downloadableDataLinkInterface.id == null : this.id.equals(downloadableDataLinkInterface.id)) &&
        (this.title == null ? downloadableDataLinkInterface.title == null : this.title.equals(downloadableDataLinkInterface.title)) &&
        (this.sortOrder == null ? downloadableDataLinkInterface.sortOrder == null : this.sortOrder.equals(downloadableDataLinkInterface.sortOrder)) &&
        (this.isShareable == null ? downloadableDataLinkInterface.isShareable == null : this.isShareable.equals(downloadableDataLinkInterface.isShareable)) &&
        (this.price == null ? downloadableDataLinkInterface.price == null : this.price.equals(downloadableDataLinkInterface.price)) &&
        (this.numberOfDownloads == null ? downloadableDataLinkInterface.numberOfDownloads == null : this.numberOfDownloads.equals(downloadableDataLinkInterface.numberOfDownloads)) &&
        (this.linkType == null ? downloadableDataLinkInterface.linkType == null : this.linkType.equals(downloadableDataLinkInterface.linkType)) &&
        (this.linkFile == null ? downloadableDataLinkInterface.linkFile == null : this.linkFile.equals(downloadableDataLinkInterface.linkFile)) &&
        (this.linkFileContent == null ? downloadableDataLinkInterface.linkFileContent == null : this.linkFileContent.equals(downloadableDataLinkInterface.linkFileContent)) &&
        (this.linkUrl == null ? downloadableDataLinkInterface.linkUrl == null : this.linkUrl.equals(downloadableDataLinkInterface.linkUrl)) &&
        (this.sampleType == null ? downloadableDataLinkInterface.sampleType == null : this.sampleType.equals(downloadableDataLinkInterface.sampleType)) &&
        (this.sampleFile == null ? downloadableDataLinkInterface.sampleFile == null : this.sampleFile.equals(downloadableDataLinkInterface.sampleFile)) &&
        (this.sampleFileContent == null ? downloadableDataLinkInterface.sampleFileContent == null : this.sampleFileContent.equals(downloadableDataLinkInterface.sampleFileContent)) &&
        (this.sampleUrl == null ? downloadableDataLinkInterface.sampleUrl == null : this.sampleUrl.equals(downloadableDataLinkInterface.sampleUrl));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.sortOrder == null ? 0: this.sortOrder.hashCode());
    result = 31 * result + (this.isShareable == null ? 0: this.isShareable.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.numberOfDownloads == null ? 0: this.numberOfDownloads.hashCode());
    result = 31 * result + (this.linkType == null ? 0: this.linkType.hashCode());
    result = 31 * result + (this.linkFile == null ? 0: this.linkFile.hashCode());
    result = 31 * result + (this.linkFileContent == null ? 0: this.linkFileContent.hashCode());
    result = 31 * result + (this.linkUrl == null ? 0: this.linkUrl.hashCode());
    result = 31 * result + (this.sampleType == null ? 0: this.sampleType.hashCode());
    result = 31 * result + (this.sampleFile == null ? 0: this.sampleFile.hashCode());
    result = 31 * result + (this.sampleFileContent == null ? 0: this.sampleFileContent.hashCode());
    result = 31 * result + (this.sampleUrl == null ? 0: this.sampleUrl.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DownloadableDataLinkInterface {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  sortOrder: ").append(sortOrder).append("\n");
    sb.append("  isShareable: ").append(isShareable).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  numberOfDownloads: ").append(numberOfDownloads).append("\n");
    sb.append("  linkType: ").append(linkType).append("\n");
    sb.append("  linkFile: ").append(linkFile).append("\n");
    sb.append("  linkFileContent: ").append(linkFileContent).append("\n");
    sb.append("  linkUrl: ").append(linkUrl).append("\n");
    sb.append("  sampleType: ").append(sampleType).append("\n");
    sb.append("  sampleFile: ").append(sampleFile).append("\n");
    sb.append("  sampleFileContent: ").append(sampleFileContent).append("\n");
    sb.append("  sampleUrl: ").append(sampleUrl).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
