/**
 * Shoppers OpenAPI
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.FrameworkSearchFilterGroup;
import io.swagger.client.model.FrameworkSortOrder;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Search criteria interface.
 **/
@ApiModel(description = "Search criteria interface.")
public class FrameworkSearchCriteriaInterface {
  
  @SerializedName("filter_groups")
  private List<FrameworkSearchFilterGroup> filterGroups = null;
  @SerializedName("sort_orders")
  private List<FrameworkSortOrder> sortOrders = null;
  @SerializedName("page_size")
  private Integer pageSize = null;
  @SerializedName("current_page")
  private Integer currentPage = null;

  /**
   * A list of filter groups.
   **/
  @ApiModelProperty(required = true, value = "A list of filter groups.")
  public List<FrameworkSearchFilterGroup> getFilterGroups() {
    return filterGroups;
  }
  public void setFilterGroups(List<FrameworkSearchFilterGroup> filterGroups) {
    this.filterGroups = filterGroups;
  }

  /**
   * Sort order.
   **/
  @ApiModelProperty(value = "Sort order.")
  public List<FrameworkSortOrder> getSortOrders() {
    return sortOrders;
  }
  public void setSortOrders(List<FrameworkSortOrder> sortOrders) {
    this.sortOrders = sortOrders;
  }

  /**
   * Page size.
   **/
  @ApiModelProperty(value = "Page size.")
  public Integer getPageSize() {
    return pageSize;
  }
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  /**
   * Current page.
   **/
  @ApiModelProperty(value = "Current page.")
  public Integer getCurrentPage() {
    return currentPage;
  }
  public void setCurrentPage(Integer currentPage) {
    this.currentPage = currentPage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrameworkSearchCriteriaInterface frameworkSearchCriteriaInterface = (FrameworkSearchCriteriaInterface) o;
    return (this.filterGroups == null ? frameworkSearchCriteriaInterface.filterGroups == null : this.filterGroups.equals(frameworkSearchCriteriaInterface.filterGroups)) &&
        (this.sortOrders == null ? frameworkSearchCriteriaInterface.sortOrders == null : this.sortOrders.equals(frameworkSearchCriteriaInterface.sortOrders)) &&
        (this.pageSize == null ? frameworkSearchCriteriaInterface.pageSize == null : this.pageSize.equals(frameworkSearchCriteriaInterface.pageSize)) &&
        (this.currentPage == null ? frameworkSearchCriteriaInterface.currentPage == null : this.currentPage.equals(frameworkSearchCriteriaInterface.currentPage));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.filterGroups == null ? 0: this.filterGroups.hashCode());
    result = 31 * result + (this.sortOrders == null ? 0: this.sortOrders.hashCode());
    result = 31 * result + (this.pageSize == null ? 0: this.pageSize.hashCode());
    result = 31 * result + (this.currentPage == null ? 0: this.currentPage.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FrameworkSearchCriteriaInterface {\n");
    
    sb.append("  filterGroups: ").append(filterGroups).append("\n");
    sb.append("  sortOrders: ").append(sortOrders).append("\n");
    sb.append("  pageSize: ").append(pageSize).append("\n");
    sb.append("  currentPage: ").append(currentPage).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
