/**
 * Shoppers OpenAPI
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Data object for sort order.
 **/
@ApiModel(description = "Data object for sort order.")
public class FrameworkSortOrder {
  
  @SerializedName("field")
  private String field = null;
  @SerializedName("direction")
  private String direction = null;

  /**
   * Sorting field.
   **/
  @ApiModelProperty(required = true, value = "Sorting field.")
  public String getField() {
    return field;
  }
  public void setField(String field) {
    this.field = field;
  }

  /**
   * Sorting direction.
   **/
  @ApiModelProperty(required = true, value = "Sorting direction.")
  public String getDirection() {
    return direction;
  }
  public void setDirection(String direction) {
    this.direction = direction;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrameworkSortOrder frameworkSortOrder = (FrameworkSortOrder) o;
    return (this.field == null ? frameworkSortOrder.field == null : this.field.equals(frameworkSortOrder.field)) &&
        (this.direction == null ? frameworkSortOrder.direction == null : this.direction.equals(frameworkSortOrder.direction));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.field == null ? 0: this.field.hashCode());
    result = 31 * result + (this.direction == null ? 0: this.direction.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FrameworkSortOrder {\n");
    
    sb.append("  field: ").append(field).append("\n");
    sb.append("  direction: ").append(direction).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
