/**
 * Shoppers OpenAPI
 * This is a Shoppers Catalogue server.  [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.  For this sample, you can use the api key `special-key` to test the authorization filters 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * 
 **/
@ApiModel(description = "")
public class FrameworkSearchAggregationValueInterface {
  
  @SerializedName("value")
  private String value = null;
  @SerializedName("metrics")
  private List<String> metrics = null;

  /**
   * Aggregation
   **/
  @ApiModelProperty(required = true, value = "Aggregation")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Metrics
   **/
  @ApiModelProperty(required = true, value = "Metrics")
  public List<String> getMetrics() {
    return metrics;
  }
  public void setMetrics(List<String> metrics) {
    this.metrics = metrics;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrameworkSearchAggregationValueInterface frameworkSearchAggregationValueInterface = (FrameworkSearchAggregationValueInterface) o;
    return (this.value == null ? frameworkSearchAggregationValueInterface.value == null : this.value.equals(frameworkSearchAggregationValueInterface.value)) &&
        (this.metrics == null ? frameworkSearchAggregationValueInterface.metrics == null : this.metrics.equals(frameworkSearchAggregationValueInterface.metrics));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    result = 31 * result + (this.metrics == null ? 0: this.metrics.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FrameworkSearchAggregationValueInterface {\n");
    
    sb.append("  value: ").append(value).append("\n");
    sb.append("  metrics: ").append(metrics).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
